# Generated by Django 6.1.1 on 2026-09-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploaded_docs/')),
                ('document_type', models.CharField(choices=[('MANUAL', 'MoSPI Manual / Operational Guide'), ('ACT', 'Collection of Statistics Act / Legislation'), ('SOP', 'Standard Operating Procedure (SOP)'), ('PLFS_REPORT', 'Periodic Labour Force Survey (PLFS) Manual'), ('CPI_GUIDE', 'Consumer Price Index (CPI/WPI) Methodology')], default='MANUAL', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('chunks_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='JSON map e.g. {"A": "...", "B": "...", "C": "...", "D": "..."}')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(help_text='Detailed rationale for correct answer')),
                ('source_citation', models.CharField(blank=True, help_text='Section/Page reference in PDF', max_length=255, null=True)),
                ('blooms_level', models.CharField(choices=[('Remembering', 'Remembering (Recall facts/definitions)'), ('Understanding', 'Understanding (Explain concepts/methodologies)'), ('Applying', 'Applying (Execute statistical procedures/CPI formula)'), ('Analyzing', 'Analyzing (Interpret survey errors & data anomalies)')], default='Understanding', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Human-in-the-loop review approval status by NSSTA Evaluators')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('answers_json', models.JSONField(default=dict, help_text='Recorded user answers per question ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
