# Generated by Django 6.1.1 on 2026-09-03 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('DOMAIN', 'Domain Competency (Statistical Systems, NAS, CPI)'), ('FUNCTIONAL', 'Functional Competency (Data Analytics, Survey Operations)'), ('BEHAVIORAL', 'Behavioral Competency (Leadership, Communication)')], default='DOMAIN', max_length=20)),
                ('official_code', models.CharField(help_text='Official FRAC Code (e.g., MoSPI-DOM-001)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearnerCompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_level', models.PositiveSmallIntegerField(default=1, help_text='Assessed Proficiency Level (1 to 5)')),
                ('last_assessed', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_scores', to='competencies.competency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner Competency Score',
                'unique_together': {('user', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='RoleCompetencyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadre', models.CharField(help_text='Target Cadre (ISS, SSS, State DES, etc.)', max_length=20)),
                ('designation', models.CharField(help_text='Target Designation (e.g. Deputy Director General, JSO)', max_length=100)),
                ('target_level', models.PositiveSmallIntegerField(default=3, help_text='Required Proficiency Level (1 to 5)')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='competencies.competency')),
            ],
            options={
                'verbose_name': 'Role Competency Target Mapping',
                'verbose_name_plural': 'Role Competency Target Mappings',
                'unique_together': {('cadre', 'designation', 'competency')},
            },
        ),
    ]
