# Generated by Django 6.1.1 on 2026-09-03 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igot_course_id', models.CharField(help_text='iGOT Portal Unique Identifier', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(default='NSSTA / DoPT', max_length=100)),
                ('url', models.URLField(default='https://igotkarmayogi.gov.in')),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_competencies', models.ManyToManyField(related_name='igot_courses', to='competencies.competency')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollments', to='igot_integration.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igot_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
